### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by sarthak212** [sarthak212/Project1#1]
As the name implies update the version of the dependencies in package-lock.json

**Comment by Aditya-Raina-1999** [comment]
i'll do this

**Comment by Aditya-Raina-1999** [comment]
i'll update the dependencies

**Comment by sarthak212** [comment]
Great it's showing some warning about some dependencies.

**Comment by Aditya-Raina-1999** [comment]
What kind of warnings? Please run 'npm outdated' once to check whether there are still any outdated packages because mine showed none

**Comment by sarthak212** [comment]
> What kind of warnings? Please run 'npm outdated' once to check whether there are still any outdated packages because mine showed none

It is showing warnings before your PR Now it's resolved.
